input:
  file: "customer.dat"
  encoding: "cp037"

copybook:
  file: "customer.cpy"

output:
  file: "customer.ascii"
  format: "flat"

validation:
  enabled: true
  method: "dual_pass"
  tolerance: 0.01
  report_file: "validation_report.html"

performance:
  threads: 1
  buffer_size: 8192